"""
asre/compliance/disclosure.py — ASRE Centralized SEBI AI Disclosure (v1.0)

Purpose
-------
Single source of truth for all SEBI-mandated AI research disclosures.
Replaces all ad-hoc console.print() disclosure strings scattered across
cli.py with one class instantiated once per session.

SEBI Requirement
----------------
SEBI Circular SEBI/HO/MIRSD/MIRSD-PoD-1/P/CIR/2024 (Dec 2024):
  AI-assisted research output must:
  (a) Identify itself as AI-generated at the point of output.
  (b) State model limitations and data dependency.
  (c) Confirm it does not constitute investment advice.
  (d) Reference the registered IA/RA responsible for the output.
  (e) Be reproducible — the same run must produce the same disclosure.

SEBI IA Regulations 2013 Reg 15(1): No implicit investment advice.
SEBI RA Regulations 2014 Reg 22(1): No misleading research language.

Placement rules (MANDATORY)
----------------------------
render_short()      → Top of every terminal session (compliance banner).
render_text()       → Bottom of full terminal output, once per session.
render_pdf_footer() → Every PDF page footer (passed to report_generator).
render_audit()      → Every DecisionLog JSONL entry.

What must NOT happen
--------------------
- Disclosure printed ad hoc inside command functions (cli.py).
- Disclosure omitted from any output surface.
- Different disclosure text for different tickers in the same session.
- Disclosure text that varies between runs with the same inputs.

Design constraints
------------------
- All render methods are pure — no side effects, no I/O.
- score_hash is populated after computation; use "pending" before.
  Call update_score_hash() when the hash is available.
- version tag format is fixed: "ASRE X.Y.Z" — do not abbreviate.

Usage (cli.py)
--------------
    # 1. Instantiate at session start (before computation)
    disclosure = DisclosureBlock(
        run_id  = decision_log.run_id,
        mode    = args.mode,
        version = ASRE_VERSION,
    )

    # 2. Print compliance banner immediately
    console.print(Panel(disclosure.render_short(), ...))

    # 3. After computation, update score hash
    disclosure.update_score_hash(score_hash)

    # 4. Print full disclosure at session end
    console.print(disclosure.render_text())

    # 5. Pass to PDF generator
    generator.generate_single_stock_report(
        ...,
        pdf_footer=disclosure.render_pdf_footer(),
    )

    # 6. Write to audit log
    decision_log.disclosure_text = disclosure.render_audit()
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

# ---------------------------------------------------------------------------
# Version
# ---------------------------------------------------------------------------

DISCLOSURE_VERSION: str = "1.0"

# ---------------------------------------------------------------------------
# Disclosure templates
# ---------------------------------------------------------------------------
# All templates use only named format fields — no positional {0}, {1}.
# Fields populated by DisclosureBlock.render_*() methods.
# ---------------------------------------------------------------------------

_FULL_TEMPLATE = """\
╔══════════════════════════════════════════════════════════════════════╗
║              SEBI AI RESEARCH DISCLOSURE                             ║
╠══════════════════════════════════════════════════════════════════════╣
║  Version   : {version:<52} ║
║  Run ID    : {run_id:<52} ║
║  Mode      : {mode:<52} ║
║  Timestamp : {timestamp:<52} ║
║  Score Hash: {score_hash:<52} ║
╠══════════════════════════════════════════════════════════════════════╣
║                                                                      ║
║  (1) This output is generated by ASRE, an AI-assisted quantitative  ║
║      research system. It is not produced by a human analyst.        ║
║                                                                      ║
║  (2) Scores are algorithmic estimates based on historical data.      ║
║      They are not deterministic predictions of future prices or      ║
║      returns.                                                        ║
║                                                                      ║
║  (3) All inputs are sourced from public data providers (Yahoo        ║
║      Finance). Data accuracy, completeness, and timeliness are       ║
║      not guaranteed.                                                 ║
║                                                                      ║
║  (4) Model outputs may vary due to estimation noise, data revision,  ║
║      cache staleness, and market regime changes. Results from        ║
║      different sessions are not guaranteed to be identical.          ║
║                                                                      ║
║  (5) This output does not constitute investment advice under SEBI    ║
║      IA Regulations 2013 or SEBI RA Regulations 2014. All           ║
║      investment decisions remain the sole responsibility of the      ║
║      registered Investment Adviser or Research Analyst.             ║
║                                                                      ║
║  (6) Generated in compliance with SEBI Circular Dec 2024 (AI        ║
║      disclosure requirements for registered intermediaries).        ║
║                                                                      ║
║  (7) Model ID : ASRE-{version:<48} ║
║      Run hash : {score_hash:<52} ║
║                                                                      ║
╚══════════════════════════════════════════════════════════════════════╝"""

_PDF_FOOTER_TEMPLATE = (
    "ASRE {version} | Run {run_id_short} | Mode {mode} | {timestamp} | "
    "AI research output only. Not investment advice. "
    "SEBI Circular Dec 2024. "
    "Hash: {score_hash_short}"
)

_AUDIT_TEMPLATE = (
    "SEBI AI Disclosure v{disclosure_version} | "
    "ASRE {version} | run={run_id} | mode={mode} | ts={timestamp} | "
    "hash={score_hash} | "
    "NOT investment advice. SEBI Circular Dec 2024."
)

_SHORT_TEMPLATE = (
    "Run ID: {run_id} | Mode: {mode} | Version: ASRE {version}\n"
    "AI-assisted research system. "
    "Output for SEBI-registered {mode} use only. "
    "Not investment advice.\n"
    "All activity is logged. Hash: {score_hash_display}"
)

_MODE_FULL_NAMES = {
    "IA" : "Investment Adviser (IA) — SEBI IA Regulations 2013",
    "RA" : "Research Analyst (RA)   — SEBI RA Regulations 2014",
}


# ---------------------------------------------------------------------------
# DisclosureBlock
# ---------------------------------------------------------------------------

class DisclosureBlock:
    """
    Encapsulates all SEBI AI disclosure text for one ASRE session.

    Instantiate once at session start. Call update_score_hash() after
    computation completes. All render methods are then available for
    terminal, PDF, and audit log output.

    Parameters
    ----------
    run_id      : UUID string from DecisionLog.run_id
    mode        : 'ia' or 'ra' (case-insensitive)
    version     : ASRE version string e.g. '2.9.0'
    score_hash  : SHA-256 hex of the score DataFrame (optional at init,
                  set via update_score_hash() after computation)
    reg_no      : SEBI registration number (redacted in output)
    """

    def __init__(
        self,
        run_id:     str,
        mode:       str,
        version:    str,
        score_hash: str = "",
        reg_no:     str = "",
    ) -> None:
        self.run_id     = run_id
        self.mode       = mode.strip().upper()
        self.version    = version.strip()
        self.score_hash = score_hash.strip() or "pending"
        self.reg_no     = reg_no.strip()
        self._created   = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # ------------------------------------------------------------------
    # Mutator
    # ------------------------------------------------------------------

    def update_score_hash(self, score_hash: str) -> None:
        """
        Set the score hash after computation completes.
        Call this before render_text(), render_pdf_footer(), render_audit().
        """
        self.score_hash = score_hash.strip() or "pending"

    # ------------------------------------------------------------------
    # Render: compliance session banner
    # ------------------------------------------------------------------

    def render_short(self) -> str:
        """
        Replaces the current 4-line compliance banner in cli.py.
        Adds AI disclosure statement absent from the original banner.

        Rendered inside a Rich Panel at session start, before any
        computation begins.

        Format
        ------
        Run ID: <uuid> | Mode: IA | Version: ASRE 2.9.0
        AI-assisted research system. Output for SEBI-registered IA use only.
        Not investment advice.
        All activity is logged. Hash: <first 16 chars or 'pending'>
        """
        score_hash_display = (
            self.score_hash[:16]
            if self.score_hash != "pending"
            else "pending"
        )
        return _SHORT_TEMPLATE.format(
            run_id             = self.run_id,
            mode               = self.mode,
            version            = self.version,
            score_hash_display = score_hash_display,
        )

    # ------------------------------------------------------------------
    # Render: full terminal disclosure
    # ------------------------------------------------------------------

    def render_text(self) -> str:
        """
        Full SEBI disclosure block for terminal output.
        Printed once at session end (in cli.py finally block).
        Contains all 7 mandatory disclosure points.

        Returns plain text with box-drawing characters.
        No Rich markup — safe for plain stdout and log files.
        """
        mode_full  = _MODE_FULL_NAMES.get(self.mode, self.mode)
        score_disp = self._truncate(self.score_hash, 52)
        run_disp   = self._truncate(self.run_id, 52)
        ver_disp   = self._truncate(self.version, 52)
        ts_disp    = self._truncate(self._created, 52)

        return _FULL_TEMPLATE.format(
            version    = ver_disp,
            run_id     = run_disp,
            mode       = self._truncate(mode_full, 52),
            timestamp  = ts_disp,
            score_hash = score_disp,
        )

    # ------------------------------------------------------------------
    # Render: PDF footer
    # ------------------------------------------------------------------

    def render_pdf_footer(self) -> str:
        """
        Compact single-line disclosure for PDF page footer.
        Passed to ASREReportGenerator — appears on every page.

        Format (max ~140 chars)
        -----------------------
        ASRE 2.9.0 | Run a3213147 | Mode IA | 2026-03-02T10:51:00Z |
        AI research output only. Not investment advice.
        SEBI Circular Dec 2024. Hash: d2f785652f66bd98
        """
        return _PDF_FOOTER_TEMPLATE.format(
            version         = self.version,
            run_id_short    = self.run_id[:8],
            mode            = self.mode,
            timestamp       = self._created,
            score_hash_short = self.score_hash[:16],
        )

    # ------------------------------------------------------------------
    # Render: audit log
    # ------------------------------------------------------------------

    def render_audit(self) -> str:
        """
        Machine-readable single-line disclosure for JSONL audit log.
        Written to DecisionLog.disclosure_text before flush().

        Format
        ------
        SEBI AI Disclosure v1.0 | ASRE 2.9.0 | run=a3213147 | mode=IA |
        ts=2026-03-02T10:51:00Z | hash=d2f785652f66bd98... |
        NOT investment advice. SEBI Circular Dec 2024.
        """
        return _AUDIT_TEMPLATE.format(
            disclosure_version = DISCLOSURE_VERSION,
            version            = self.version,
            run_id             = self.run_id,
            mode               = self.mode,
            timestamp          = self._created,
            score_hash         = self.score_hash,
        )

    # ------------------------------------------------------------------
    # Render: Rich Panel (for cli.py console.print())
    # ------------------------------------------------------------------

    def render_rich_banner(self) -> str:
        """
        Rich-markup version of render_short() for the compliance banner panel.
        Only call this when Rich is available (HAS_RICH = True in cli.py).

        Usage in cli.py
        ---------------
            console.print(Panel(
                disclosure.render_rich_banner(),
                title="[bold white]🔐 Compliance Session[/bold white]",
                border_style="cyan",
            ))
        """
        score_display = (
            self.score_hash[:16]
            if self.score_hash != "pending"
            else "[dim]pending[/dim]"
        )
        return (
            f"[dim]Run ID :[/dim]  [cyan]{self.run_id}[/cyan]\n"
            f"[dim]Mode   :[/dim]  [bold]{_MODE_FULL_NAMES.get(self.mode, self.mode)}[/bold]\n"
            f"[dim]Version:[/dim]  ASRE [bold]{self.version}[/bold]\n"
            f"[dim]Hash   :[/dim]  {score_display}\n"
            f"\n"
            f"[yellow]AI-assisted research system.[/yellow] "
            f"Output for SEBI-registered [bold]{self.mode}[/bold] use only.\n"
            f"[dim]Not investment advice. "
            f"All activity is logged for SEBI compliance.[/dim]"
        )

    # ------------------------------------------------------------------
    # Render: plain banner (fallback when Rich is unavailable)
    # ------------------------------------------------------------------

    def render_plain_banner(self) -> str:
        """
        Plain-text fallback for render_rich_banner().
        Used when HAS_RICH = False in cli.py.
        """
        sep = "─" * 72
        return (
            f"\n{sep}\n"
            f"  COMPLIANCE SESSION\n"
            f"  Run ID  : {self.run_id}\n"
            f"  Mode    : {_MODE_FULL_NAMES.get(self.mode, self.mode)}\n"
            f"  Version : ASRE {self.version}\n"
            f"  AI-assisted research system. "
            f"Not investment advice.\n"
            f"  All activity is logged for SEBI compliance.\n"
            f"{sep}\n"
        )

    # ------------------------------------------------------------------
    # Equality / reproducibility check
    # ------------------------------------------------------------------

    def is_reproducible_with(self, other: "DisclosureBlock") -> bool:
        """
        Return True if two DisclosureBlock instances would produce identical
        render_audit() output (same run = same disclosure).

        Used in tests to verify audit trail consistency.
        """
        return (
            self.run_id     == other.run_id
            and self.mode   == other.mode
            and self.version == other.version
            and self.score_hash == other.score_hash
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _truncate(text: str, width: int) -> str:
        """
        Truncate text to width characters, appending '…' if truncated.
        Used to keep fixed-width template columns aligned.
        """
        if len(text) <= width:
            return text
        return text[: width - 1] + "…"

    def __repr__(self) -> str:
        return (
            f"DisclosureBlock(run_id={self.run_id[:8]}..., "
            f"mode={self.mode}, version={self.version}, "
            f"hash={self.score_hash[:8]}...)"
        )


# ---------------------------------------------------------------------------
# Module-level smoke test
# ---------------------------------------------------------------------------

def _smoke_test() -> None:
    """
    Runs on import. Verifies all render methods produce non-empty output
    and contain the mandatory SEBI disclosure elements.
    Raises AssertionError if any check fails.
    """
    d = DisclosureBlock(
        run_id     = "a3213147-4127-4cc2-8135-c39fca0becab",
        mode       = "ia",
        version    = "2.9.0",
        score_hash = "d2f785652f66bd984a21b8c5e3a90123",
    )

    short = d.render_short()
    assert "a3213147" in short,             "render_short: run_id missing"
    assert "IA"        in short,            "render_short: mode missing"
    assert "2.9.0"     in short,            "render_short: version missing"
    assert "Not investment advice" in short, "render_short: disclosure missing"
    assert "\n"        in short,            "render_short: must be multi-line"

    full = d.render_text()
    assert "SEBI AI RESEARCH DISCLOSURE" in full, "render_text: header missing"
    assert "investment advice"           in full,  "render_text: advice disclaimer missing"
    assert "SEBI Circular Dec 2024"      in full,  "render_text: circular reference missing"
    assert "a3213147"                    in full,  "render_text: run_id missing"
    assert "d2f78565"                    in full,  "render_text: hash missing"

    footer = d.render_pdf_footer()
    assert "ASRE 2.9.0"           in footer, "render_pdf_footer: version missing"
    assert "a3213147"             in footer, "render_pdf_footer: run_id missing"
    assert "Not investment advice" in footer, "render_pdf_footer: disclaimer missing"
    assert len(footer)            < 300,     "render_pdf_footer: too long for footer"

    audit = d.render_audit()
    assert "Disclosure v1.0"   in audit, "render_audit: version tag missing"
    assert "run=a3213147"      in audit, "render_audit: run_id missing"
    assert "mode=IA"           in audit, "render_audit: mode missing"
    assert "NOT investment"    in audit, "render_audit: disclaimer missing"

    rich = d.render_rich_banner()
    assert "cyan" in rich or "bold" in rich, "render_rich_banner: no Rich markup"

    # Reproducibility: same inputs → same audit line
    d2 = DisclosureBlock(
        run_id     = "a3213147-4127-4cc2-8135-c39fca0becab",
        mode       = "ia",
        version    = "2.9.0",
        score_hash = "d2f785652f66bd984a21b8c5e3a90123",
    )
    assert d.render_pdf_footer() == d2.render_pdf_footer(), \
        "render_pdf_footer is not reproducible"

    # update_score_hash works
    d3 = DisclosureBlock(run_id="test", mode="ra", version="2.9.0")
    assert "pending" in d3.render_short()
    d3.update_score_hash("abc123")
    assert "pending" not in d3.render_short()
    assert "abc123"[:16]  in d3.render_short()


_smoke_test()


# ---------------------------------------------------------------------------
# __all__
# ---------------------------------------------------------------------------

__all__ = [
    "DisclosureBlock",
    "DISCLOSURE_VERSION",
]
